{:config {:name :tutorial, :description "Tutorial Recording", :order 0}
 :data
 [
  [:node-create [] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:value [:main :my-counter] nil 1]
  [:transform-enable [:main :my-counter] :increment-counter [{:io.pedestal.app.messages/type :inc, :io.pedestal.app.messages/topic [:my-counter]}]]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 4.33]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 8]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 13]
  [:node-create [:main :other-counters] :map]
  [:node-create [:main :other-counters "abc"] :map]
  [:value [:main :other-counters "abc"] nil 8]
  [:node-create [:main :other-counters "xyz"] :map]
  [:value [:main :other-counters "xyz"] nil 4]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 20]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 39]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 13]
  :break
  [:value [:main :other-counters "abc"] 8 9]
  [:value [:main :average-count] 4.33 4.67]
  [:value [:main :max-count] 8 9]
  [:value [:main :total-count] 13 14]
  :break
  [:value [:main :my-counter] 1 2]
  [:value [:main :average-count] 4.67 5]
  [:value [:main :total-count] 14 15]
  [:value [:pedestal :debug :dataflow-time-avg] 20 19]
  [:value [:pedestal :debug :dataflow-time] 13 11]
  :break
  [:value [:main :other-counters "xyz"] 4 5]
  [:value [:main :average-count] 5 5.33]
  [:value [:main :total-count] 15 16]
  [:value [:pedestal :debug :dataflow-time-avg] 19 18]
  [:value [:pedestal :debug :dataflow-time] 11 12]
  :break
  [:value [:main :other-counters "abc"] 9 10]
  [:value [:main :average-count] 5.33 5.67]
  [:value [:main :max-count] 9 10]
  [:value [:main :total-count] 16 17]
  [:value [:pedestal :debug :dataflow-time] 12 13]
  :break
  [:value [:main :my-counter] 2 3]
  [:value [:main :average-count] 5.67 6]
  [:value [:main :total-count] 17 18]
  [:value [:pedestal :debug :dataflow-time] 13 12]
  :break
  [:value [:main :my-counter] 3 4]
  [:value [:main :average-count] 6 6.33]
  [:value [:main :total-count] 18 19]
  [:value [:pedestal :debug :dataflow-time-avg] 18 17]
  [:value [:pedestal :debug :dataflow-time] 12 11]
  :break
  [:value [:main :my-counter] 4 5]
  [:value [:main :average-count] 6.33 10]
  [:value [:main :total-count] 19 20]
  [:value [:pedestal :debug :dataflow-time] 11 12]
  :break
  [:value [:main :other-counters "abc"] 10 11]
  [:value [:main :average-count] 10 10.5]
  [:value [:main :max-count] 10 11]
  [:value [:main :total-count] 20 21]
  [:value [:pedestal :debug :dataflow-time] 12 13]
 ]}